version: "3"

services:
  ps_account_web:
    image: prestashop/prestashop:${PS_VERSION}
    container_name: ps_acc_web
    env_file: .env
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost"]
        interval: 30s
        timeout: 10s
        retries: 5
    ports:
      - 80:80
    networks:
      - services_accounts-net

  ps_account_db:
    image: mysql:5.7
    container_name: ps_acc_db
    env_file: .env
    networks:
      - services_accounts-net

networks:
  services_accounts-net:
    external: true
