const i18n = require('i18n');

module.exports = {
  Products: {
    demo_1: {
      id: 1,
      name: i18n.__('Hummingbird printed t-shirt'),
      reference: 'demo_1',
      category: i18n.__('Men'),
      shortDescription: i18n.__('Regular fit, round neckline, short sleeves. Made of extra long staple pima cotton.'),
      description: i18n.__('Symbol of lightness and delicacy, the hummingbird evokes curiosity and joy. Studio Design\' '
        + 'PolyFaune collection features classic products with colorful patterns, inspired by the traditional japanese '
        + 'origamis. To wear with a chino or jeans. The sublimation textile printing process provides an exceptional '
        + 'color rendering and a color, guaranteed overtime.'),
      regularPrice: 28.919,
      price: 23.90,
      finalPrice: 23.14,
      discount: '20%',
      quantity: 2400,
      coverImage: 'hummingbird-printed-t-shirt.jpg',
      combination: {
        size: ['S', 'M', 'L', 'XL'],
        color: [i18n.__('White'), i18n.__('Black')],
      },
      status: true,
    },
    demo_3: {
      id: 2,
      name: i18n.__('Hummingbird printed sweater'),
      reference: 'demo_3',
      category: i18n.__('Women'),
      price: 35.09,
      quantity: 2100,
      status: true,
    },
    demo_5: {
      id: 4,
      name: i18n.__('The adventure begins Framed poster'),
      reference: 'demo_5',
      category: i18n.__('Art'),
      price: 29.00,
      quantity: 1500,
      status: true,
    },
    demo_6: {
      id: 3,
      name: i18n.__('The best is yet to come\' Framed poster'),
      reference: 'demo_6',
      category: i18n.__('Art'),
      price: 29.00,
      quantity: 1500,
      status: true,
    },
    demo_8: {
      id: 16,
      name: i18n.__('Mountain fox notebook'),
      reference: 'demo_18',
      category: i18n.__('Stationery'),
      price: 15.48,
      quantity: 1200,
      status: true,
    },
    demo_13: {
      id: 8,
      name: i18n.__('Mug Today is a good day'),
      reference: 'demo_13',
      category: i18n.__('Home Accessories'),
      price: 14.28,
      quantity: 300,
      status: true,
    },
    demo_14: {
      id: 19,
      name: i18n.__('Customizable mug'),
      reference: 'demo_14',
      category: i18n.__('Home Accessories'),
      price: 13.90,
      quantity: 300,
      status: true,
    },
    demo_18: {
      id: 12,
      name: i18n.__('Mountain fox - Vector graphics'),
      reference: 'demo_18',
      category: i18n.__('Art'),
      price: 9,
      quantity: 300,
      status: true,
    },
  },
};
