name: Bug report
description: Something doesn't work like it should? Tell us!
title: "[Bug]: "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: lib-version
    attributes:
      label: Modules testing library version
      description: Which version of the modules testing library are you using?
      placeholder: ex. 1.0.1
    validation:
      required: true
  - type: dropdown
    id: prestashop-version
    attributes:
      label: PrestaShop version
      multiple: true
      description: Which PrestaShop version are you testing on?
      options:
        - 1.7.7
        - 1.7.6
        - 1.7.5
        - 1.7.4
    validation:
      required: true
  - type: textarea
    id: other-information
    attributes:
      label: Other information
      descripiton: ex. Nodejs version, Browser type etc.
  - type: textarea
    id: bug-description
    attributes:
      label: What happened? / Describe the bug
      description: Also tell us, what did you expect to happen?
    validation:
      required: true
  - type: textarea
    id: reproducible
    attributes:
      label: Code snippet to reproduce your bug
      description: Help us help you! Put down a short code snippet that illustrates your bug and that we can run and debug locally. This will be automatically formatted into code, so no need for backticks.
      render: shell
      placeholder: |
        const VersionSelectResolver = require('@resolvers/versionSelectResolver');
        const versionSelectResolver = new VersionSelectResolver(global.PS_VERSION);

        const loginPage = versionSelectResolver.require('BO/login/index.js');
        const dashboardPage = versionSelectResolver.require('BO/dashboard/index.js');
  - type: textarea
    id: screenshots
    attributes:
      label: Attached screenshots or logs
      description: Please add screenshots here or logs if needed to understand the issue
