name: Quality Control

on: [push, pull_request]

jobs:
  js-linter:
    name: JS linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint
