name: Quality Control

on: [push, pull_request]

jobs:
  js-linter:
    name: JS linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: lint js dependencies
        uses: PrestaShopCorp/github-action-lint-js/12@v1.0
        with:
          cmd: yarn

  units-tests:
    name: unit testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run start:test:units
